### ISSUE TITLE
AboutMap, tests 01 & 02 & 03

### ISSUE THREAD

**Issue by cynic** [StephenJHunt/FSharpKoans#3]
These would be even nicer if they were tail recursive.
![star-trek-make-it-so-450x270](https://user-images.githubusercontent.com/408406/36979580-a4dc3996-2090-11e8-8209-3ba14b5c740f.jpg)

**Comment by Dane-Horn** [comment]
Same as with the first issue, the list concatenation happens within a parameter being passed with the recursive call and so these should all still be tail recursive.

**Comment by cynic** [comment]
Agree, as before ... but would it be possible to make them more efficient?
