### ISSUE TITLE
AboutOtherListFunctions, tests 02 & 03 & 06 & 07

### ISSUE THREAD

**Issue by cynic** [StephenJHunt/FSharpKoans#5]
Could you make these tail recursive?

**Comment by Dane-Horn** [comment]
Same as issue 1 and 3.

**Comment by Dane-Horn** [comment]
Fixed all issues, we just added let bindings so the calls are explicitly tail recursive, but we still don't understand why they weren't tail recursive before.

**Comment by cynic** [comment]
That's my bad, these are indeed tail recursive.  I'm so used to associating concat with code such as `myList @ doWhatever rest` that as soon as I saw the `@`, I didn't parse much else!

It is inefficient, though.  Could you make it more efficient?
